# Generated by Django 4.2.5 on 2023-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_book_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='0', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='chap',
            field=models.CharField(max_length=2000),
        ),
    ]
