# Generated by Django 4.2.5 on 2023-11-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_book_image_alter_book_chap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
