# Generated by Django 4.2.5 on 2024-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', '館藏中'), ('borrowed', '外借中')], default='available', max_length=20),
        ),
    ]
