# Generated by Django 4.2.5 on 2024-01-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_alter_book_image'),
        ('mysite', '0006_alter_book_status'),
    ]

    operations = [
    ]
